### ISSUE TITLE
No output rows in SMETANA detailed.tsv

### ISSUE THREAD

**Issue by eltanin4** [cdanielmachado/smetana#15]
I tried to run SMETANA on a community of 19 models (generated using genomic DNA using CarveMe) in a custom medium (M9 + glucose) by defining a custom media library (I copied the example library.tsv and replaced the M9[glyc] medium with an M9[gluc] medium by swapping the glycerol row with a glc__D row).

Initially, I received a warning for "MIP: no solution found for non-interacting community".

If I use --flavor bigg, I don't get this warning, but I don't get any output (other than column names) in detailed.tsv.

I am happy to provide my model files and other files to reproduce this error. The models were generated with CarveMe and gapfilled on an M9 medium.

**Comment by cdanielmachado** [comment]
Yes, please use `--flavor bigg` in SMETANA if you use the latest version of CarveMe (or you used an older version of CarveMe with the `--fbc2` flag, now the default).

When you run SMETANA in detailed model, it will enumerate cross-feeding interactions for species with obligatory dependencies. If each species can grow alone, there will be no obligatory dependencies, and the result is an empty list.

If you want to explore non-obligatory dependencies as well, you can use the `--no-coupling` flag.
