### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by pbelmann** [cdanielmachado/smetana#18]
Running Smetana (master branch, commit d2b10434d)  with 4 models and with parameters `  --solver cplex  -v  --flavor bigg --detailed `  returns  `segmentation fault`. Models were generated using carveme. Please let me know if I can help with debugging.

Output:
```
Loading community: all
Running SCS for community all on medium minimal...
Running MUS for community all on medium minimal...
Segmentation fault (core dumped) 
```

**Comment by pbelmann** [comment]
I also noticed that sometimes for the same input `segmentation fault` is returned and sometimes not.

**Comment by cdanielmachado** [comment]
Hi, this is more likely an issue with cplex. Seg faults usually arise from pre-compiled binaries.

Did you install the correct cplex version for your python environment?

**Comment by pbelmann** [comment]
I installed python3.8 in an virtual environment and install the python library using setup.py that ships with cplex. (`cplex/python/3.8/x86-64_linux/setup.py`).
However I noticed that if I set the `use_bool` flag to false it works just fine.

**Comment by cdanielmachado** [comment]
`use_bool` is not a flag in SMETANA... are you referring to the cplex installation ?

**Comment by pbelmann** [comment]
Sorry, I mean `use_pool` and not `use_bool`

**Comment by cdanielmachado** [comment]
No problem. That flag uses cplex solution pools for speeding up the enumeration of multiple solutions. Maybe there is a bug in this particular version of cplex when that option is used. Which version are you using?

**Comment by pbelmann** [comment]
> No problem. That flag uses cplex solution pools for speeding up the enumeration of multiple solutions. Maybe there is a bug in this particular version of cplex when that option is used. Which version are you using?

 20.1.0.0

**Comment by pbelmann** [comment]
I can confirm that cplex version 12.9.0 works without issues.

**Comment by cdanielmachado** [comment]
Perfect, thanks!
