### ISSUE TITLE
Co-occurrent bacteria

### ISSUE THREAD

**Issue by ntromas** [cdanielmachado/smetana#19]
Hi, 
I would like to test which metabolites pathways are complemented (if there is) between two taxa that are highly co-occurrent and that have co-evolved.
I produced .xml with gapseq (I did not use any medium ref as these bacteria were never cultivated).
I then just run Smetana on the two .xml files with -d parameters.
Would you recommend this approach?
Thanks for you help&suggestion

Cheers,

Nico

**Comment by cdanielmachado** [comment]
Yes, that approach makes sense. 

Best regards,
Daniel

**Comment by ntromas** [comment]
Hi Daniel,

Thanks for your answer. So I played with -d and -g. I have a small community of different taxa (different phyla).
I got pretty high MRO (>0.75) and even higher (>0.85) with co-evolved small community.
However, I always got warnings like "Gene association for reaction R_rxn... is not DNF". Do you know if it is because I am using a gapseq models?
Thanks for your help,

Cheers,
Nico

**Comment by cdanielmachado** [comment]
Hi Nico,

That's not a problem since gene associations are not used in SMETANA. 

Daniel

**Comment by ntromas** [comment]
Hi Daniel,

Thanks!
