### ISSUE TITLE
Atomic weight not listed for elements

### ISSUE THREAD

**Issue by Rachita-Kumar** [cdanielmachado/smetana#24]
Hi Daniel,

I'm trying to use SMETANA for a few ModelSEED models, and I was wondering if you could help me with the following issue. I used the --molweight as you had recommended it.

> UserWarning: Atomic weight not listed for elements: {'R'}                                                                                                                         warn(f"Atomic weight not listed for elements: {missing}")

Thanks very much,
Rachita

**Comment by cdanielmachado** [comment]
Hi Rachita,

That is not an error, it is just a warning that some compounds contain an "R" atom, which is not really a chemical element, it is a pseudo-code to represent a generic residue in the molecule. The software will just ignore the atomic weight of that residue. I think there is no reason to worry about this warning. The simulations should still give meaningful results.

Best regards,
Daniel
