### ISSUE TITLE
Query regarding nature of gapfilled carveme models for smetana use

### ISSUE THREAD

**Issue by shreyanshumale** [cdanielmachado/smetana#25]
I wanted to know if I should use the 'initialized' models (--gapfill -i ) or the unconstrained ones (just --gapfill ) produced by carveme for my smetana analyses? (As it seems to make a difference)

Please let me know!

Thanks,
Shreyansh

**Comment by cdanielmachado** [comment]
Hi Shreyansh,

That is strange, SMETANA should ignore the initialized medium and calculate a new one. In any case, I think it is best if you use the unconstrained models.

Best regards,
Daniel
