### ISSUE TITLE
smetana running error: Assertion failed: teta >= 0.0

### ISSUE THREAD

**Issue by EmmettPeng** [cdanielmachado/smetana#26]
Hi,

I'm trying to use SMETANA to analyze my models created by carveme. After pip installing, it reported error as below:

```
Assertion failed: teta >= 0.0
Error detected in file simplex/spxchuzr.c at line 292
Aborted (core dumped)
```

I did not find any useful solutions after googling about it so please help to troubleshoot. Thanks.

Emmett

**Comment by cdanielmachado** [comment]
Hi Emmett,

It seems you are using GLPK. We have only tested smetana with CPLEX, so I cannot guarantee that it will work with other solvers.

**Comment by EmmettPeng** [comment]
> Hi Emmett,
> 
> It seems you are using GLPK. We have only tested smetana with CPLEX, so I cannot guarantee that it will work with other solvers.

Thanks for your prompt reply. I actually do not know that what solver it would use. I did install CPLEX and it worked fine while I'm using CarveMe. Why does it use other solver here? How can I lead it to CPLEX?

Emmett

**Comment by cdanielmachado** [comment]
It must be using GLPK through OptLang, since we do not support GLPK directly, but we do have an interface for OptLang. However, it should only default to OptLang if it cannot import the CPLEX library...

What happens if you run the following in your terminal `python -c 'import cplex; print(cplex.__version__)'` ?

**Comment by EmmettPeng** [comment]
It shows:
```
(carveme) pengxi@ubuntu_r740:~/hotspring/NGS/best_bins/binset$ python -c 'import cplex; print(cplex.__version__)'
20.1.0.0
```

**Comment by EmmettPeng** [comment]
It seems like the system uses the wrong smetana. Now the problem goes away.
