### ISSUE TITLE
Cross-feeding interaction untraceable metabolites

### ISSUE THREAD

**Issue by iuliachiciudean** [cdanielmachado/smetana#29]
Hi Daniel,

I generated my Smetana microbial community interactions, but I can not seem to find a logic in the exchanged metabolites. Is there any way to trace a metabolite production pathway in the donor organism?

I am verifying the BlastKoala-generated pathway of my donor organism, and I am looking at the metabolic model using Fluxer (https://fluxer.umbc.edu/). 

For example,  from the Smetana metabolic interactions, it appears that my donor organism is donating H2S, but I can not find a pathway for H2S production in the genome. By visualising the GEM with Fluxer I can see that H2S is needed (not produced) in the assimilatory sulfate reduction pathway to produce L-Cysteine.

So how is Smetana deducing that the metabolite is produced by the microorganism?
Any suggestions on how I can trace the Smetana production of the metabolites in the genome or GEM?

Thank you!
Best regards,
Iulia

**Comment by iuliachiciudean** [comment]
Hi Daniel,

This is the FVA result from CNApy for 2 metabolites that are donated according to Smetana (scour 1).
H2S:
![H2S](https://user-images.githubusercontent.com/53013742/150488041-aab380cf-9e3f-4ad3-9ddb-2781e363a147.png)
Methanol:
![Methanol](https://user-images.githubusercontent.com/53013742/150488441-02e754da-72c3-4bb2-98bd-a28ed3c64002.png)

Is this what you suggested to look for?
Those results are not what I have expected for an organism that is donating those compounds for community growth.

Do you think something went wrong during the Smetana calculations?
I can send you the metabolic model .XML file.

Best regards,

Iulia

**Comment by cdanielmachado** [comment]
It seems that your model can secrete H2S, so the output from smetana is correct. If that is not the expected behavior you might need to manually curate your model.
