### ISSUE TITLE
Identifying minimal medium composition in detailed interactions

### ISSUE THREAD

**Issue by franciscozorrilla** [cdanielmachado/smetana#30]
Hi Daniel,

I have a 4 species community for which I calculated 100 detailed interaction simulations using the `--molweight` flag. Now I am interested in getting an idea of the minimal media compostion used in detailed interactions, does it make sense to run a number of global simulations with the `--debug` flag and extract the media composition in the row associated with the MRO of the community?

```
community	medium	key1	key2	data
all	complete	mip	ni	ca2,cl,cobalt2,cu2,fe3,gam,k,mg2,mn2,nac,no,o2,pi,pnto__R,ribflv,so4,thm,val__L,zn2
all	complete	mip	i	ca2,cl,cobalt2,cu2,fe3,gam,k,mg2,mn2,nac,o2,pi,pnto__R,ribflv,so4,thm,zn2
all	complete	mro	community	ca2,cl,cobalt2,cu2,fe3,gam,k,mg2,mn2,nac,o2,pi,pnto__R,ribflv,so4,thm,zn2
all	complete	mro	CHCC10675	ca2,cl,cobalt2,cu2,fe3,glyc,k,mg2,mn2,nh4,pi,so4,thm,val__L,zn2
all	complete	mro	CHCC4895	ca2,cl,cobalt2,cu2,fe3,gam,k,mg2,mn2,nac,pi,pnto__R,ribflv,so4,thm,zn2
all	complete	mro	CHCC5614	ca2,cl,cobalt2,cu2,fe3,fol,gam,k,mg2,mn2,o2,pi,ribflv,so4,thm,val__L,zn2
all	complete	mro	CHCC6086	ca2,cl,cobalt2,cu2,fe2,gly,h,k,mg2,mn2,o2,pi,so4,thm,val__L,zn2
```

Thanks and best wishes,
Francisco

**Comment by cdanielmachado** [comment]
Hi Francisco,

Yes, I think that makes sense. Either mro/community or mip/i (interacting), in principle should be the same.

Best regards,
Daniel
