### ISSUE TITLE
Comparative Analysis of MIP and MRO Across Variable MAG Compositions and Investigating Cross-Feeding Pathways in Microbial Communities

### ISSUE THREAD

**Issue by Noob-Monkey** [cdanielmachado/smetana#44]
Hi Daniel,
     I'm calculating MIP and MRO based on MAGs assembled from different samples using SMETANA. The number of MAGs assembled varies between each metagenomic sample. Can I compare MIP and MRO between different samples directly? Would the results obtained in this way be meaningful? Here are my two sets of results, calculated based on communities composed of 16 MAGs and 20 MAGs, respectively.
      community	medium	size	mip	mro
      all	                complete	 20	19	0.5905817174515235
      community	medium	size	mip	mro
      all	                complete	16	11	0.6201550387596899

      Another question is, once I've identified a cross-feeding relationship between two species, A and B, using SMETANA, such as A providing D-Ribose to B, how can I determine the metabolic processes through which A generates D-Ribose and the processes through which B utilizes this D-Ribose?

donor                       compound       receiver
o__QNBC01              M_rib__D_e     o__UBA7950
o__Humimicrobiales  M_cellb_e        o__Methanosarcinales
o__DHVEG-1            M_cellb_e        o__Methanosarcinales
o__Humimicrobiales  M_man1p_e    o__Dehalococcoidales

Thank you in advance!
JackChang

**Comment by franciscozorrilla** [comment]
To identify the metabolic processes associated with exchanged metabolites in your donor and reciever you could just run individual FBA simulations and visualise internal fluxes associated with your pathway of interest.

In the [original SMETANA publication ](https://www.pnas.org/doi/full/10.1073/pnas.1421834112#supplementary-materials)they normalize MIP by total community members, while [in a more recent study](https://www.nature.com/articles/s41559-020-01353-4) they do indeed separate the score by community sizes. It probably depends on the question you are trying to ask.

**Comment by Noob-Monkey** [comment]
Dear Francisco

Thank you very much for your kind response and for developing metagem. As a beginner in bioinformatics, I must say that metagem has been incredibly helpful for my research on microbial interactions in cold seep sediments. Your work has provided a solid foundation for my studies.

In your previous message, you mentioned running individual Flux Balance Analysis (FBA) simulations and visualizing internal fluxes associated with specific pathways of interest. Could you kindly suggest any existing software or pipelines that could help me accomplish this? At my current stage, I find some of the more complex bioinformatics workflows a bit overwhelming, so a more straightforward tool or method would be much appreciated.

Thank you again for your assistance and for your continued contributions to the field. I look forward to hearing from you soon.

Best regards,

JackChang

**Comment by franciscozorrilla** [comment]
Dear JackChang,

Here are some suggestions that come to mind:

1. [Escher](https://escher.github.io/) + [Escher-FBA](https://sbrg.github.io/escher-fba/#/): No-code, GUI-based visualisation and simple analysis. This is nice for toy models, simple models, and for visually sanity checking a GEM of interest. You can knock out different reactions and see how metabolism would adapt accordingly.
2. [Fluxxer](https://fluxer.umbc.edu/): Similar to above, with a few extra/advanced features e.g. merging models, alternative layouts/visualisations, spanning trees, and shortest-k path. The last one is really cool in my opinion, as you can check for the shortest pathways that connect two metabolites of interest (e.g. glucose -> biomass).
3. [COBRApy](https://opencobra.github.io/cobrapy/) + [reframed](https://reframed.readthedocs.io/en/latest/): These are two popular python code libraries for metabolic modelling. You can load models, constrain the environment/media, and run flux balance analysis. You can then summarize and load the output flux files into R or your preferred software for visualisation and downstream analysis. Here is an [example script](https://github.com/Chrats-Melkonian/mi_cheese/blob/main/code/04_individual_GEM_sims.py) from a recent collaboration 🧀 : it loops through a set of models and runs FBA + FVA under different media conditions.

I am happy to hear that metaGEM has provided a useful platform for learning and launching your metagenomics-driven metabolic modelling research 💎 

Best wishes,
Francisco

**Comment by Noob-Monkey** [comment]
Dear Francisco,

Thank you very much for your valuable suggestions and for introducing me to various tools for metabolic modeling. I have found Fluxxer particularly helpful, especially its model merging functionality, which has significantly aided in resolving some of the challenges I was facing. 

Best regards,
JackChang
