### ISSUE TITLE
Pip install not working in python 2.7

### ISSUE THREAD

**Issue by rafafernandes96** [cdanielmachado/smetana#6]
I tried installing using pip install in python 2.7:
(carveme) rafael@rafael-HP-Pavilion-15-Notebook-PC:~$ pip install git+https://github.com/cdanielmachado/smetana
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting git+https://github.com/cdanielmachado/smetana
  Cloning https://github.com/cdanielmachado/smetana to /tmp/pip-req-build-0y0vXC
  Running command git clone -q https://github.com/cdanielmachado/smetana /tmp/pip-req-build-0y0vXC
ERROR: Could not find a version that satisfies the requirement reframed (from smetana==1.2.0) (from versions: none)
ERROR: No matching distribution found for reframed (from smetana==1.2.0)

Although, it worked with python 3.6

**Comment by cdanielmachado** [comment]
I am currently dropping support for Python 2 in all of the tools I am currently maintaining. Please use Python 3 :)

**Comment by cdanielmachado** [comment]
Also, it is better to run `pip install smetana` to get the latest stable release. If you install directly from git you will get development versions that might not be stable.
