### ISSUE TITLE
Model loading Issue  with Smetana

### ISSUE THREAD

**Issue by NTDevika** [cdanielmachado/smetana#7]
I am encountering the following error upon running smetana (Input single species models generated from Carveme).
I tried giving even the test files (uploaded in the githubpage), but encountering the same error.
Can you please help me out t sort this issue?

 command used  **smetana ec_glc_ko.xml ec_nh4_ko.xml --flavor cobra**
![SMETANA_Error](https://user-images.githubusercontent.com/29056867/75648728-f71d2480-5c76-11ea-828d-5f94f48639ee.png)

**Comment by cdanielmachado** [comment]
In this case, you are using our example models which are using `fbc2` flavor, not `cobra`.  Please remove the flavor option (fbc2 is the default).

**Comment by NTDevika** [comment]
I am using smetana to generate the cross fed metabolites.
**Input Command**
 **smetana Lactobacillus_paracasei_ATCC_334.xml V_harveyi_QT520.xml --mediadb constrained_media_comp.tsv --flavor cobra**
**Output**
community       medium  size    mip     mro
all     complete        2       n/a     0.7692307692307693

why is the mip score showing n/a?
Further in smetana is their anyway , the program will output the list or name of cross-fed metabolites.
Thank You!!

**Comment by cdanielmachado** [comment]
MIP is calculated by comparing the number of nutrients required when the species grow together vs growing alone. If they cannot grow alone, then MIP cannot be calculated.
