### ISSUE TITLE
Is it possible to generate the list of cross-fed metabolites between the pair of organism

### ISSUE THREAD

**Issue by NTDevika** [cdanielmachado/smetana#8]
I am using smetana to generate the cross fed metabolites.
**Input Command**
 **smetana Lactobacillus_paracasei_ATCC_334.xml V_harveyi_QT520.xml --mediadb constrained_media_comp.tsv --flavor cobra**
**Output**
community       medium  size    mip     mro
all     complete        2       n/a     0.7692307692307693

why is the mip score showing n/a?
Further in smetana is their anyway , the program will output the list or name of cross-fed metabolites.
Thank You!!

_Originally posted by @NTDevika in https://github.com/cdanielmachado/smetana/issues/7#issuecomment-594460979_

**Comment by cdanielmachado** [comment]
Yes, you must run smetana in detailed mode as described in the documentation:

https://smetana.readthedocs.io/en/latest/usage.html#global-vs-detailed-mode
